//
// Created by GreenMuffin on 2026/1/20.
//

#ifndef LEARNCOMPILERPRINCIPLES_CLI_H
#define LEARNCOMPILERPRINCIPLES_CLI_H


#define VERSION 0.1.0
#define MAX_LINE_LEN 1024


#endif //LEARNCOMPILERPRINCIPLES_CLI_H